//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario_libros
    {
        public int Inventario { get; set; }
        public Nullable<int> Enlace { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tip_fondo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Ult_inv { get; set; }
        public string Ctrl_RFID { get; set; }
        public string Estado { get; set; }
        public string Tomvol { get; set; }
        public string Biblioteca { get; set; }
        public string Coleccion { get; set; }
        public string Ejemplares { get; set; }
        public string Estado_Material { get; set; }
    }
}
