//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int Id { get; set; }
        public string COD1 { get; set; }
        public string COD2 { get; set; }
        public string COD3 { get; set; }
        public string COD4 { get; set; }
        public string COD5 { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public string Contenido { get; set; }
        public string palabrasClave { get; set; }
        public int Enlace { get; set; }
        public string Pri_isbn { get; set; }
        public string Pri_tifb { get; set; }
        public string img { get; set; }
        public string Tip_coleccion { get; set; }
        public string Compl { get; set; }
        public string Edicion { get; set; }
        public string Lugar { get; set; }
        public string Editorial { get; set; }
        public string Anyo { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public string Paginas { get; set; }
        public string Tipomater { get; set; }
        public string URL { get; set; }
        public string Idioma { get; set; }
        public string IdEditorial { get; set; }
        public string Anyo_reimp { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado_eliminacion { get; set; }
        public string contenidoOK { get; set; }
    }
}
